### ISSUE TITLE
web3: should provide enumerable network object

### ISSUE THREAD

**Issue by vojtechsimetka** [rsksmart/rif-ui#27]
The web3 provider should give more information like `chainId`. It should also expose the name not only as a string but as an enum.

https://github.com/rsksmart/rif-ui/blob/master/src/providers/Web3Provider.tsx#L39

**Comment by farinalvaro** [comment]
After discussing with @vojtechsimetka we agreed to have a local copy of [this JSON](https://chainid.network/chains.json) and expose not only the `networkName` and `chainId` but all that information on the provider as it would be useful for the consumer. We will also refer to [their MIT](https://github.com/ethereum-lists/chains) on our docs.
So the conclusion is that we will provide a `NetworkInfo` object instead of an enumerable.
